// Master subject list for the CBT portal (backend).
// Mirror of `frontend/src/lib/subjects.ts` — keep in sync.

export const CORE_SUBJECTS = [
  'English Language',
  'General Mathematics',
  'Civic Education',
  'Health Education',
  'Physical Education',
];

export const SCIENCE_SUBJECTS = [
  'Physics',
  'Chemistry',
  'Biology',
  'Further Mathematics',
  'Agricultural Science',
  'Geography',
  'Computer Studies',
  'Data Processing',
  'Technical Drawing',
  'Animal Husbandry',
  'Fisheries',
  'Horticulture and Crop Production',
  'Livestock Farming',
  'Food and Nutrition',
];

export const COMMERCIAL_SUBJECTS = [
  'Economics',
  'Financial Accounting',
  'Commerce',
  'Marketing',
  'Office Practice',
  'Insurance',
  'Business Studies',
  'Store Keeping',
  'Store Management',
  'Book Keeping',
  'Business Management',
  'Salesmanship',
  'Principles of Cost Accounting',
  'Typing',
  'Shorthand',
  'Keyboard',
];

export const ART_SUBJECTS = [
  'Literature in English',
  'Government',
  'History',
  'Christian Religious Studies',
  'Islamic Religious Studies',
  'French',
  'Arabic',
  'Music',
  'Visual Arts',
  'Fine Art',
  'Yoruba',
  'Igbo',
  'Hausa',
  'Edo',
  'Efik',
  'Ibibio',
  'Nigerian Language',
  'Photography',
  'Ceramics',
  'Picture Making',
  'Painting and Decorating',
];

export const ICT_SUBJECTS = [
  'Computer Studies',
  'Data Processing',
  'Computer Science',
  'ICT',
  'Information Communication Technology',
  'Graphic Design',
  'Printing Practice',
  'Solar Photovoltaic Installation and Maintenance',
  'Computer Hardware and GSM Repairs',
  'GSM Phones Maintenance and Repairs',
];

export const VOCATIONAL_SUBJECTS = [
  'Home Management',
  'Home Economics',
  'Clothing and Textiles',
  'Catering Craft Practice',
  'Garment Making',
  'Tourism',
  'Mining',
  'Blocklaying',
  'Bricklaying and Concrete Work',
  'Dyeing and Bleaching',
  'Beauty and Cosmetology',
  'Cosmetology',
  'Fashion Design and Garment Making',
  'Leather Goods Manufacturing',
  'Textile Trade',
  'Carpentry and Joinery',
  'Furniture Making',
  'Auto Mechanics',
  'Auto Body Repair and Spray Painting',
  'Auto Electrical Work',
  'Auto Parts Merchandising',
  'Air Conditioning and Refrigeration',
  'Welding and Fabrication',
  'Plumbing and Pipe Fitting',
  'Basic Electricity',
  'Applied Electricity',
  'Electronics',
  'Basic Electronics',
  'Electronics Works',
  'Metal Work',
  'Woodwork',
  'Wood Work',
  'Machine Woodworking',
  'Building Construction',
];

export const ALL_SUBJECTS: string[] = Array.from(
  new Set([
    ...CORE_SUBJECTS,
    ...SCIENCE_SUBJECTS,
    ...COMMERCIAL_SUBJECTS,
    ...ART_SUBJECTS,
    ...ICT_SUBJECTS,
    ...VOCATIONAL_SUBJECTS,
  ])
).sort();

export const JAMB_SUBJECTS: string[] = [
  'English Language',
  'General Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Economics',
  'Government',
  'Literature in English',
  'Christian Religious Studies',
  'Islamic Religious Studies',
  'Commerce',
  'Financial Accounting',
  'Geography',
  'History',
  'Agricultural Science',
  'Further Mathematics',
  'Technical Drawing',
  'French',
  'Yoruba',
  'Igbo',
  'Hausa',
  'Computer Studies',
  'Data Processing',
  'Insurance',
  'Marketing',
  'Office Practice',
  'Music',
  'Fine Arts',
];
